[package]
name = "otlp-stdout-kinesis-extension-layer"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
description = "OpenTelemetry Lambda extension for sending otlp data to Kinesis"

[dependencies]
tokio.workspace = true
tracing.workspace = true
aws-config.workspace = true
aws-sdk-kinesis = { version = "1", default-features = false, features = ["rt-tokio"] }
lambda-extension = { version = "0.11.0" }
uuid = { version = "1.0", features = ["v4"] }
