[package]
name = "custom-stdout-exporter"
version = "0.1.0"
edition = "2021"
authors = ["AWS Lambda Team"]
license = "MIT"
rust-version = "1.70.0"
description = "A span exporter that writes OpenTelemetry spans to stdout in OTLP format"
readme = "README.md"
keywords = ["opentelemetry", "otlp", "tracing", "aws", "lambda"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[dependencies]
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-proto.workspace = true
tokio.workspace = true
async-trait.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
